var store_seeds = [
  { "name": "John's",
    "ingredients": [
      "Apples",
      "Orange",
      "Bananas",
      "Pears",
      "Mango",
      "Tomatoes",
      "Garlic",
      "Eggplant",
      "Potato",
      "Green Onion",
      "Mushroom",
      "Zucchini",
      "Squash",
      "Onions",
      "Bell Pepper",
      "Cucumber",
    ]
  },
  { "name": "Goody's",
    "ingredients": [
      "Apples",
      "Orange",
      "Bananas",
      "Pears",
      "Lemon",
      "Limes",
      "Garlic",
      "Eggplant",
      "Potato",
      "Green Onion",
      "Mushroom",
      "Zucchini",
      "Squash",
      "Tomato",
      "Onion",
      "Bell Pepper",
      "Cilantro",
      "Cucumber",
    ]
  },
  { "name": "Sixth",
    "ingredients": [
      "Apples",
      "Orange",
      "Bananas",
      "Cauliflower",
      "Tomatoes",
      "Garlic",
      "Eggplant",
      "Potato",
      "Green Onion",
      "Mushroom",
      "Zucchini",
      "Squash",
      "Onions",
      "Bell Pepper",
      "Cucumber",
    ]
  },
  { "name": "The Village",
    "ingredients": [
      "Apples",
      "Orange",
      "Bananas",
      "Cantaloupe",
      "Grapes",
      "Grapefruit",
      "Honeydew",
      "Mango",
      "Kiwi",
      "Blackberries",
      "Strawberries",
      "Tangerines",
      "Lemon",
      "Lime",
      "Blueberries",
      "Potatoes",
      "Sweet Potato",
      "Yam",
      "Avocado",
      "Bell Pepper",
      "Eggplant",
      "Cucumber",
      "Tomatoes",
      "Lettuce",
      "Onions",
      "Mushrooms",
      "Carrots",
      "Jalapeno",
      "Cilantro",
    ]
  },
  { "name": "Earl's",
    "ingredients": [
      "Apples",
      "Orange",
      "Bananas",
      "Mangos",
      "Grapes",
      "Cabbage",
      "Broccolini",
      "Tomatoes",
      "Garlic",
      "Eggplant",
      "Potato",
      "Green Onion",
      "Mushroom",
      "Zucchini",
      "Squash",
      "Onions",
      "Bell Pepper",
      "Cucumber",
    ]
  },
  { "name": "Roger's",
    "ingredients": [
      "Pineapple",
      "Oranges",
      "Apples",
      "Cantaloupe",
      "Strawberry",
      "Bananas",
      "Tomatoes",
      "Pomegranate",
      "Pears",
      "Mango",
      "Potato",
      "Yam",
      "Avocado",
      "Yellow Onions",
      "Red Onions",
      "Celery",
      "Asparagus",
      "Broccoli",
      "Zucchini",
      "Squash",
      "Napa",
      "Eggplant",
      "Cucumber",
      "Cauliflower",
      "Mushroom",
      "Carrots",
      "Bell Peppers",
      "Garlic",
      "Jalapenos",
    ]
  },
  { "name": "Ralphs",
    "ingredients": []
  },
]
module.exports = store_seeds;
